import Header from "@/components/layout/Header";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ReduxProvider from "@/components/ReduxProvider";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Books App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins`}>
        <ReduxProvider>
          <Header />
          <ToastContainer />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
